name: "Changelog checks"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-commits-lint-check:
    name: "Lint PR title"
    runs-on: "ubuntu-latest"
    steps:
      - name:
        uses: amannn/action-semantic-pull-request@b4011711b945563fe63ffa9654c38d1782532528
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
