name: "Changelog checks"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional-commits-lint-check:
    name: "Lint PR title"
    runs-on: "ubuntu-latest"
    steps:
      - name:
        uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
