on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
name: CI - Release
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  tuf:
    needs: tests
    #if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
    with:
      cli-name: tuf
  tuf-client:
    needs: tests
    #if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
    with:
      cli-name: tuf-client
