on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
name: Release
jobs:
  tests:
    uses: ./.github/workflows/workflow-tests.yml
  tuf:
    uses: ./.github/workflows/workflow-rel-tuf.yml
    needs: tests
  tuf-client:
    uses: ./.github/workflows/workflow-rel-tuf-client.yml
    needs: tests
