on:
  push:
    tags:
      - "v*"
  # workflow_run:
  #   workflows: ["Run tests"]
  #   branches: [master]
  #   types:
  #     - completed
name: Release
jobs:
  tests:
    uses: ./.github/workflows/workflow-tests.yml
  tuf:
    uses: ./.github/workflows/workflow-rel-tuf.yml
    needs: tests
  tuf-client:
    uses: ./.github/workflows/workflow-rel-tuf-client.yml
    needs: tests
