on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "^v[0-9]+.[0-9]+.[0-9]+"
name: CI
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  tuf:
    needs: tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
    with:
      cli-name: tuf
  tuf-client:
    needs: tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
    with:
      cli-name: tuf-client
