on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*"
name: CI
jobs:
  tests:
    uses: ./.github/workflows/workflow-tests.yml
  tuf:
    needs: tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/workflow-rel-tuf.yml
    with:
      cli-name: tuf
  tuf-client:
    needs: tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/workflow-rel-tuf.yml
    with:
      cli-name: tuf-client
