on: [push, pull_request]
name: goreleaser
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade iso8601 requests securesystemslib six tuf
    - name: Format Unix
      if: runner.os == 'Linux'
      run: test -z $(go fmt ./...)
    - name: Test
      run: go test -race -covermode atomic -coverprofile='profile.cov' ./...
    - name: Send coverage
      if: runner.os == 'Linux'
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  release-server:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: write cosign.key to environment
        run: 'echo "$COSIGN_KEY" > .github/cosign.key'
        shell: bash
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      - name: install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.1'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v0.180.2'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
  release-cli:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: write cosign.key to environment
        run: 'echo "$COSIGN_KEY" > .github/cosign.key'
        shell: bash
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      - name: install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.1'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v0.180.2'
          args: release --config ./.goreleaser_client.yaml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
